### ISSUE TITLE
laravel 5.4 FatalThrowableError

### ISSUE THREAD

**Issue by ghost** [daylerees/sanitizer#18]
Call to undefined method Illuminate\Foundation\Application::share() in vendor/daylerees/sanitizer/src/SanitizerServiceProvider.php:16,
As of laravel 5.4 share has been removed. You will have to use the singleton instead.

**Comment by antonioreyna** [comment]
same problem

**Comment by daylerees** [comment]
Fixed in merged PR. Thanks.
